name: Convert JSON to CSV

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 수동 실행을 허용하는 설정 추가
  schedule:
    - cron: '0 0 1 * *'  # 매달 첫 번째 날 자정에 실행

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Run conversion script
        run: python convert_to_csv.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add notion_backup.csv || echo "No changes to commit"
          git commit -m "Convert JSON to CSV" || echo "Nothing to commit"
          git push || echo "Push failed"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GITHUB_TOKEN 사용
