name: Monthly Notion Backup

on:
  schedule:
    - cron: '0 0 31 1,3,5,7,8,10,12 *'
    - cron: '0 0 30 4,6,9,11 *'
    - cron: '0 0 28 2 *'
  workflow_dispatch:  # 수동 실행을 위한 트리거 추가

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run backup script
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      run: python notion_backup.py

    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Monthly backup $(date +'%Y-%m-%d')" && git push)
